title: Stefano Boring
description: > # this means to ignore newlines until "baseurl:"
  writer/digitalartist
permalink: ':title/'
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://estervigilante.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Stefano Boring # add your name
author-img: stefano-boring.jpg # add your photo
#about-author: la descrizione e' nel file _layouts/main.html
social-instagram: ester_satomi
social-email: stefanoboring@gmail.com
social-tumblr: stefanoboring

# Disqus
discus-identifier: estervigilante

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
permalink: /:categories/:title
plugins:
  - jekyll-paginate


exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

pagination:
  enabled: true
  debug: false
  per_page: 50
  sort_reverse: true

paginate: 20
paginate_path: "/page/:num/"


sass:
    sass_dir: css/scss
