title: Stefano boring
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://boringandsad.githubio" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Stefano Boring # add your name
author-img: stefano-boring.jpg # add your photo
#about-author: la descrizione e' nel file _layouts/main.html
social-instagram: ester_satomi
social-email: stefanoboring@gmail.com
social-tumblr: stefanoboring

# Disqus
discus-identifier: stefanoboring

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
permalink: /:categories/:title
plugins:
  - jekyll-paginate


exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

pagination:
  enabled: true
  debug: false
  per_page: 50
  sort_reverse: true

# autopages:
#   enabled: true
#   categories:
#     layouts:
#       - cat.html
#     title: 'Posts in category :cat'
#     permalink: '/category/:cat'
#     slugify:
#       mode: 'default'
#       case: true
#   tags:
#     enabled: false
#   collections:
#     enabled: false

paginate: 20


sass:
    sass_dir: css/scss
